# .github/workflows/normer.yml
on: [push, pull_request]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v3
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
